---
name: etcd

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: kubo-etcd
  version: latest
- name: bosh-dns
  sha1: 9231b7c7d2f6aa85e0cb77fdeef7add54fdb3f1a
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.2.0
  version: 0.2.0


features:
  use_dns_addresses: true

addons:
- name: bosh-dns
  include:
    stemcells:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
        client:
          tls: ((/dns_healthcheck_client_tls))

instance_groups:
- name: etcd
  azs: [z1, z2, z3]
  instances: 1
  persistent_disk_type: 10GB
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: etcd-bosh-dns-aliases
    release: kubo-etcd
  - name: etcd
    release: kubo-etcd
    properties:
      etcd:
        dns_health_check_host: 169.254.0.2 # this is the default BOSH DNS nameserver
        advertise_urls_dns_suffix: etcd.cfcr.internal
        require_ssl: true
        peer_require_ssl: true
        delete_data_dir_on_stop: false
        ca_cert: ((tls-etcd-server.ca))
        server_cert: ((tls-etcd-server.certificate))
        server_key: ((tls-etcd-server.private_key))
        client_cert: ((tls-etcd-client.certificate))
        client_key: ((tls-etcd-client.private_key))
        peer_ca_cert: ((tls-etcd-peer.ca))
        peer_cert: ((tls-etcd-peer.certificate))
        peer_key: ((tls-etcd-peer.private_key))

update:
  serial: true
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
- name: etcd_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: tls-etcd-server
  type: certificate
  options:
    ca: etcd_ca
    common_name: etcd.cfcr.internal
    extended_key_usage:
    - server_auth
    - client_auth
    alternative_names:
    - "*.etcd.cfcr.internal"
    - etcd.cfcr.internal
- name: tls-etcd-client
  type: certificate
  options:
    extended_key_usage:
    - client_auth
    ca: etcd_ca
    common_name: etcdClient
- name: tls-etcd-peer
  type: certificate
  options:
    extended_key_usage:
    - server_auth
    - client_auth
    ca: etcd_ca
    common_name: etcd.cfcr.internal
    alternative_names:
    - "*.etcd.cfcr.internal"
    - etcd.cfcr.internal

- name: /dns_healthcheck_tls_ca
  opsname: global_dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca
- name: /dns_healthcheck_server_tls
  opsname: global_dns_healthcheck_server_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth
- name: /dns_healthcheck_client_tls
  opsname: global_dns_healthcheck_client_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth
